import { ApplyStatus, Industry, Job, RecruitType, VipPlan } from './types';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    company: 'ByteDance',
    industry: Industry.INTERNET,
    type: RecruitType.FALL,
    locations: ['北京', '上海', '深圳'],
    status: ApplyStatus.NOT_APPLIED,
    startDate: '2023-08-01',
    endDate: '2023-10-31',
    noWrittenTest: false,
    roles: ['Frontend', 'Backend', 'Product'],
    announcementLink: '#',
    applyLink: '#',
    remark: '早投递早筛选，HC多多',
    batch: '25',
    salary: '25k-45k*15',
    isNew: true,
  },
  {
    id: '2',
    company: 'Tencent',
    industry: Industry.INTERNET,
    type: RecruitType.FALL,
    locations: ['深圳', '广州'],
    status: ApplyStatus.APPLIED,
    startDate: '2023-08-10',
    endDate: '2023-11-15',
    noWrittenTest: false,
    roles: ['Game Dev', 'Frontend'],
    announcementLink: '#',
    applyLink: '#',
    remark: '游戏部门缺人',
    batch: '25',
    salary: '22k-40k*16',
    isNew: true,
  },
  {
    id: '3',
    company: 'CICC',
    industry: Industry.FINANCE,
    type: RecruitType.INTERN,
    locations: ['北京', '上海', '香港'],
    status: ApplyStatus.WRITTEN_TEST,
    startDate: '2023-09-01',
    endDate: '2023-09-30',
    noWrittenTest: true,
    roles: ['Analyst', 'IT Support'],
    announcementLink: '#',
    applyLink: '#',
    remark: '需尽快入职',
    batch: '26',
    salary: '300/day',
    isNew: false,
  },
  {
    id: '4',
    company: 'State Grid',
    industry: Industry.SOE,
    type: RecruitType.SPRING,
    locations: ['全国'],
    status: ApplyStatus.NOT_APPLIED,
    startDate: '2024-03-01',
    endDate: '2024-04-15',
    noWrittenTest: false,
    roles: ['Electrical Engineer', 'Computer Science'],
    announcementLink: '#',
    applyLink: '#',
    remark: '主要看学校背景',
    batch: '25',
    salary: '15k-20k',
    isNew: false,
  },
  {
    id: '5',
    company: 'Microsoft',
    industry: Industry.FOREIGN,
    type: RecruitType.FALL,
    locations: ['北京', '苏州', '上海'],
    status: ApplyStatus.INTERVIEW,
    startDate: '2023-08-15',
    endDate: '2023-11-01',
    noWrittenTest: true,
    roles: ['SDE', 'PM'],
    announcementLink: '#',
    applyLink: '#',
    remark: '英文面试',
    batch: '25',
    salary: '28k-35k*14',
    isNew: false,
  },
   {
    id: '6',
    company: 'ICBC',
    industry: Industry.FINANCE,
    type: RecruitType.FALL,
    locations: ['北京', '杭州'],
    status: ApplyStatus.REJECTED,
    startDate: '2023-09-01',
    endDate: '2023-10-20',
    noWrittenTest: false,
    roles: ['FinTech', 'Teller'],
    announcementLink: '#',
    applyLink: '#',
    remark: '笔试很难',
    batch: '25',
    salary: '12k-22k',
    isNew: false,
  }
];

/** 仅作兜底，实际价位以 GET /vip/plans 接口下发为准 */
export const VIP_PLANS: VipPlan[] = [
  { id: '1_month', name: '月度会员', durationLabel: '1个月', price: 8.8, originalPrice: 19.9, tag: '尝鲜' },
  { id: '3_month', name: '季度会员', durationLabel: '3个月', price: 16.6, originalPrice: 49.9, tag: '超值推荐' },
  { id: 'lifetime', name: '永久会员', durationLabel: '永久', price: 29.9, originalPrice: 99.9, tag: '超值' },
];

export const MAX_FREE_QUERIES = 3;