-- ============================================================
-- 校招信息聚合站 - Supabase (PostgreSQL) 建表脚本
-- 与 JPA 实体一致，可直接在 Supabase SQL Editor 中执行
-- ============================================================

-- 1. 招聘职位表 job
CREATE TABLE IF NOT EXISTS job (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id BIGINT UNIQUE,
    company         VARCHAR(128) NOT NULL,
    industry        VARCHAR(32)  NOT NULL,
    recruit_type    VARCHAR(32)  NOT NULL,
    locations       VARCHAR(512),
    start_date      TEXT,
    end_date        TEXT,
    no_written_test TEXT         NOT NULL DEFAULT 'false',
    roles           VARCHAR(512),
    announcement_link VARCHAR(512),
    apply_link      VARCHAR(512),
    remark          VARCHAR(1024),
    batch           VARCHAR(8),
    salary          VARCHAR(64),
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_industry ON job (industry);
CREATE INDEX IF NOT EXISTS idx_recruit_type ON job (recruit_type);
CREATE INDEX IF NOT EXISTS idx_end_date ON job (end_date);
CREATE INDEX IF NOT EXISTS idx_created_at ON job (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS job_announcement_id_key ON job (announcement_id);

-- 2. 用户表 app_user（含迭代 v1 邀请奖励字段 bonus_queries）
CREATE TABLE IF NOT EXISTS app_user (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    open_id             VARCHAR(64)  NOT NULL,
    union_id            VARCHAR(64),
    nickname            VARCHAR(64),
    avatar              VARCHAR(512),
    query_count         INTEGER      NOT NULL DEFAULT 0,
    query_count_reset_at DATE,
    bonus_queries       INTEGER      NOT NULL DEFAULT 0,
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP    NOT NULL,
    CONSTRAINT uk_open_id UNIQUE (open_id)
);

-- 若表已存在且无 bonus_queries，可单独执行：
-- ALTER TABLE app_user ADD COLUMN IF NOT EXISTS bonus_queries INTEGER NOT NULL DEFAULT 0;

-- 3. 用户投递进度表 user_job_status（依赖 job、app_user 存在即可，未建外键以与 JPA 一致）
CREATE TABLE IF NOT EXISTS user_job_status (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    job_id     BIGINT       NOT NULL,
    status     VARCHAR(32)  NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_user_job UNIQUE (user_id, job_id)
);

CREATE INDEX IF NOT EXISTS idx_ujs_user_id ON user_job_status (user_id);
CREATE INDEX IF NOT EXISTS idx_ujs_job_id ON user_job_status (job_id);

-- 4. 会员表 user_member（方案 A）
CREATE TABLE IF NOT EXISTS user_member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    plan_id    VARCHAR(32)  NOT NULL,
    start_at   TIMESTAMP    NOT NULL,
    end_at     TIMESTAMP    NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_um_user_id ON user_member (user_id);

-- 5. 支付订单表 payment_order
CREATE TABLE IF NOT EXISTS payment_order (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no   VARCHAR(64)  NOT NULL,
    user_id    BIGINT       NOT NULL,
    plan_id    VARCHAR(32)  NOT NULL,
    amount     NUMERIC(10,2) NOT NULL,
    pay_channel VARCHAR(16),
    trade_no   VARCHAR(64),
    status     VARCHAR(16)  NOT NULL,
    paid_at    TIMESTAMP,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uk_order_no UNIQUE (order_no)
);

CREATE INDEX IF NOT EXISTS idx_po_user_id ON payment_order (user_id);

-- ========== 迭代 v1：留存与转化 新增表 ==========

-- 6. 内推码库 referral_code（方案6，VIP 专享）
CREATE TABLE IF NOT EXISTS referral_code (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name    VARCHAR(128) NOT NULL,
    code            VARCHAR(128) NOT NULL,
    contributor_id  BIGINT,
    usage_count     INTEGER NOT NULL DEFAULT 0,
    is_valid        BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rc_company ON referral_code (company_name);
CREATE INDEX IF NOT EXISTS idx_rc_valid ON referral_code (is_valid);

-- 6. 邀请关系 user_invitation（方案3）
CREATE TABLE IF NOT EXISTS user_invitation (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inviter_id    BIGINT       NOT NULL,
    invitee_id    BIGINT,
    invite_code   VARCHAR(64)  NOT NULL,
    reward_status VARCHAR(32)  NOT NULL DEFAULT 'pending',
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_ui_invite_code UNIQUE (invite_code)
);
CREATE INDEX IF NOT EXISTS idx_ui_inviter ON user_invitation (inviter_id);
CREATE INDEX IF NOT EXISTS idx_ui_invitee ON user_invitation (invitee_id);

-- 可选：让 Supabase 的 id 自增序列与已有数据兼容（若先导数据再让应用写，可跳过）
-- 若完全由应用插入且用 IDENTITY，无需执行下面注释部分：
-- SELECT setval(pg_get_serial_sequence('job', 'id'), COALESCE((SELECT MAX(id) FROM job), 1));
-- SELECT setval(pg_get_serial_sequence('app_user', 'id'), COALESCE((SELECT MAX(id) FROM app_user), 1));
-- 其余表同理
